#+TITLE: mPower Project Documentation

* Introduction
:PROPERTIES:
:CUSTOM_ID: s1
:END:

This file is documented all the necessary information related to this
repository.


* Packages to be Installed
:PROPERTIES:
:CUSTOM_ID: s2
:END:


** Synapse Bridge

The synapseclient package provides an interface to Synapse, a collaborative,
open-source research platform that allows teams to share data, track analyses,
and collaborate, providing support for:

+ Integrated presentation of data, code and text
+ Fine grained access control
+ Provenance tracking

The ~synapseclient~ package lets you communicate with the cloud-hosted Synapse
service to access data and create shared data analysis projects from within
Python scripts or at the interactive ~Python~ console. Other Synapse clients exist
for ~R~, ~Java~, and the web. The ~Python~ client can also be used from the command
line.

If you’re just getting started with Synapse, have a look at the Getting Started
guides for Synapse.

*** Installation
:PROPERTIES:
:CUSTOM_ID: s3
:END:

 The synapseclient package is available from PyPI. It can be installed or
 upgraded with pip. Note that synapseclient requires ~Python 3~, and if you have
 both ~Python 2~ and ~Python 3~ installations your system, the ~pip~ command
 associated with ~Python 3~ may be named ~pip3~ to distinguish it from a ~Python
 2~ associated command. Prefixing the ~pip~ installation with sudo may be
 necessary if you are installing ~Python~ into a shared system installation of
 ~Python~.

#+begin_src bash
 (sudo) pip3 install (--upgrade) synapseclient[pandas, pysftp]
#+end_src

 You are also able to use ~Conda~ interface to install the library:

#+begin_src bash
 conda install -c bioconda synapseclient
#+end_src
 
The dependencies on pandas and pysftp are optional. The Synapse
~synapseclient.table~ feature integrates with Pandas. Support for sftp is
required for users of SFTP file storage. Both require native libraries to be
compiled or installed separately from prebuilt binaries.

Source code and development versions are [[https://github.com/Sage-Bionetworks/synapsePythonClient][available on Github]]. Installing from
source:

#+begin_src bash
  git clone git://github.com/Sage-Bionetworks/synapsePythonClient.git
  cd synapsePythonClient
#+end_src

You can stay on the master branch to get the latest stable release or check out
the develop branch or a tagged revision:

#+begin_src bash
git checkout <branch or tag>
#+end_src

Next, either install the package in the site-packages directory python
~setup.py~ install or python ~setup.py~ develop to make the installation follow
the head without having to reinstall:

#+begin_src bash
python setup.py <install or develop>
#+end_src

