from data_loader.data_loader import DataLoader
from data_loader.load_tapping_data import TappingDataLoader
from data_loader.load_memory_data import MemeoryDataLoader
from data_loader.load_walking_data import WalkingDataLoader
from data_loader.load_voice_data import VoiceDataLoader
from data_loader.load_accumulated_data import AccumulatedDataLoader
