from loader.data_loader import DataLoader
from loader.load_tapping_data import TappingDataLoader
from loader.load_memory_data import MemeoryDataLoader
from loader.load_walking_data import WalkingDataLoader
from loader.load_voice_data import VoiceDataLoader
from loader.load_accumulated_data import AccumulatedDataLoader
